spring:
  application:
    name: achacha

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: achacha
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 5MB # 파일 하나 당 최대 용량
      max-request-size: 15MB # 모든 파일의 최대 용량

  profiles:
    group:
      local:
        - local
      prod:
        - prod
      test:
        - test

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

clova:
  ocr:
    api-url: ${CLOVA_OCR_API_URL}
    secret-key: ${CLOVA_OCR_SECRET_KEY}

ai-service:
  api-url: ${AI_SERVICE_URL}
