spring:
  application:
    name: achacha

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  cloud:
    aws:
      s3:
        region: ap-northeast-2
        enabled: true # Spring Cloud AWS 스타터가 S3 관련 빈 자동 구성
      credentials:
        access-key: ${AWS_ACCESS_TOKEN}
        secret-key: ${AWS_SECRET_TOKEN}

  profiles:
    group:
      local:
        - local
      prod:
        - prod
      test:
        - test

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

clova:
  ocr:
    api-url: ${CLOVA_OCR_API_URL}
    secret-key: ${CLOVA_OCR_SECRET_KEY}

ai-service:
  api-url: ${AI_SERVICE_URL}

aws:
  s3:
    bucket: achacha-bucket
  cloudfront:
    domain: d23wsj9ifltpil.cloudfront.net
    keypair-id: ${AWS_CLOUDFRONT_KEYPAIR_ID}
    private-key: ${AWS_CLOUDFRONT_PRIVATE_KEY}