spring:
  application:
    name: achacha

  profiles:
    group:
      local:
        - local
      prod:
        - prod
      test:
        - test

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
