version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile-local
    restart: unless-stopped
    volumes:
      # 서비스 계정 키 파일을 컨테이너 내부로 마운트
      - ./firebaseServiceAccountKey.json:/app/firebaseServiceAccountKey.json
    ports:
      - "8081:8081"  # 호스트 8081, 컨테이너 내부 8080
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      FIREBASE_PATH: /app/firebaseServiceAccountKey.json
    networks:
      - achacha-network

networks:
  achacha-network:
    external: true  # 메인 서비스에서 생성한 네트워크를 사용