version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - achacha-network

networks:
  achacha-network:
    name: achacha-network
    external: true